from __future__ import annotations

"""Central UI sizing and spacing tokens for consistent layouts."""

# Root window layout
ROOT_MARGIN_H = 12
ROOT_MARGIN_TOP = 10
ROOT_MARGIN_BOTTOM = 10
ROOT_SPACING = 10
SECTION_SPACING = 8
GRID_SPACING = 14

# Generic control heights
BUTTON_HEIGHT_SM = 28
BUTTON_HEIGHT_MD = 36
BUTTON_HEIGHT_MODE = 38
BUTTON_HEIGHT_LG = 40
BUTTON_HEIGHT_XL = 44
INPUT_HEIGHT_MD = 34
SLIDER_HEIGHT_MD = 30
TOOL_BUTTON_WIDTH_MD = 40
TOOL_BUTTON_HEIGHT_MD = 32

# Panel layout defaults
PANEL_CONTENT_MARGIN_H = 16
PANEL_CONTENT_MARGIN_V = 12
PANEL_LAYOUT_SPACING = 10

# Name list layout defaults
NAME_ROW_HORIZONTAL_SPACING = 4
NAMES_PANEL_LAYOUT_SPACING = 6
NAMES_PANEL_ACTION_TOP_MARGIN = 2

# Overlay layout defaults
OVERLAY_CARD_MARGIN_H = 26
OVERLAY_CARD_MARGIN_V = 22
OVERLAY_LAYOUT_SPACING = 10
OVERLAY_TOP_ROW_SPACING = 6
OVERLAY_ACTION_SPACING_BASE = 8
OVERLAY_ACTION_SPACING_RESULT = 14
OVERLAY_ACTION_SPACING_OCR = 80

# Profile dropdown layout defaults
PROFILE_HEADER_LEFT_MARGIN = 10
PROFILE_TOGGLE_WIDTH = 44
PROFILE_ROW_HEIGHT = 28
